version: '3'
services:
  mysqldb:
    image: mysql
    container_name: wordpress_mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chengxulvtu
      MYSQL_USER: chengxulvtu
      MYSQL_PASSWORD: 123456

  wordpress:
    depends_on:
      - mysqldb
    image: wordpress
    container_name: wordpress_chengxulvtu
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_mysql:3306
      WORDPRESS_DB_NAME: chengxulvtu
      WORDPRESS_DB_USER: chengxulvtu
      WORDPRESS_DB_PASSWORD: 123456
    volumes:
      - ./html:/var/www/html